<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1 (Total recall)

Subsetting: to select<br>
Indexing: to select one element <br>
Slicing: to select a range of elements <br>
Masking: _using True/False answer to a condition to mask so that only the True subset can be seen._

## Exercise 2 (Show me the 'odd' letters)

In [1]:
import numpy as np

In [41]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

filter_np_array=np_array_2d[:,0]    # : is to select all, 0 is to choose all the index 0
int_array=filter_np_array.astype(int)

rem_array=int_array%2
mask_array=rem_array==1
int_array[mask_array]

array([1, 3, 5, 7, 9])

## Exercise 3 

In [40]:
np_array=np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

cond_1=np_array < 50 # create mask for <50
np_array[cond_1]=-1 # assign -1 to True values

cond_2=np_array >50 
np_array[cond_2]=1

cond_3=np_array==50
np_array[cond_3]=0
print(np_array)



[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
