<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [1]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
py_list=["a1","b2","c3","d4","e5","f6","g7","h8","i9","j10"]
np_array=np.array(py_list)

# pick one
x=py_list # or
x=np_array

In [3]:
py_list[1:6:2]

['b2', 'd4', 'f6']

In [4]:
py_list[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

In [6]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
mask=np_array %3 == 0
np_array[mask]

array([3, 6, 9])

In [10]:
mask.sum()      #counts number of trues

np.int64(3)

In [8]:
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np_array//2 #Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [11]:
np_array%2  #Remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [12]:
np_array[~mask]

array([ 1,  2,  4,  5,  7,  8, 10])

In [13]:
np_array[(np_array>3)&(np_array<8)]     # "&" means "AND"

array([4, 5, 6, 7])

In [14]:
np.logical_and(np_array>3,np_array<3)

array([False, False, False, False, False, False, False, False, False,
       False])

## 1.2 Arrays only | Subsetting by masking

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d=np.array(py_list_2d)

In [17]:
py_list_2d[3:][0]

[4, 'D']

In [18]:
np_array_2d[3,0]    # Only for Numpy

np.str_('4')

In [19]:
np_array_2d[3:,1]   # Only for Numpy

array(['D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

## 1.4 Growing lists

In [20]:
x=[1,2]+[3]
print(x)
x= x + [2]
print(x)
x= x + [3]
print(x)
x= x + [4]
print(x)
x

[1, 2, 3]
[1, 2, 3, 2]
[1, 2, 3, 2, 3]
[1, 2, 3, 2, 3, 4]


[1, 2, 3, 2, 3, 4]

# Some loose ends

## 1.5 Tuples

## 1.6 Be VERY careful when copying

## Footnotes