<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

Python Lists

In [15]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

Numpy Arrays

In [1]:
import numpy as np

In [14]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionary

In [13]:
superhero_info={
    "Natasha Romanoff":"Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange":"Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [2]:
py_super_names=["Black widow", "Iron Man","Doctor Strange"]
py_real_names=["Natasha Romanoff","Tony Stark","Stephen Strange"]

In [4]:
py_real_names[0]    # python starts counting from 0 so 0=1st term

'Natasha Romanoff'

In [5]:
py_super_names[0]

'Black widow'

In [9]:
py_super_names[2] # counts left to right from 0 for positive index

'Doctor Strange'

In [10]:
py_super_names[-1]  # negative index counts from the back of the list

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [12]:
superhero_info={
    "Natasha Romanoff":"Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange":"Doctor Strange"
}

In [17]:
superhero_info["Natasha Romanoff"] 
# acts like a lock and key, only provides output based on input

'Black Widow'

In [18]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [19]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [22]:
py_superhero_info=[['Natasha Romanoff','Black Widow'],
                   ['Tony Stark', 'Iron Man'],
                   ['Stephen Strange','Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [23]:
py_list_2d=[[1,"A"],[2,"B"],[3,"C"],[4,"D"],
            [5,"E"],[6,"F"],[7,"G"],[8,"H"],
            [9,"I"],[10,"J"]]

np_array_2d=np.array(py_list_2d) 
# reusing a python list to create new numpy array

In [33]:
print(len(py_list_2d))
print(len(np_array_2d))
np_array_2d.shape

# len() is used to know no. of elements in list/ array
# shape does not have () since it is not a function but a property of numpy array

10
10


(10, 2)

## 2.2 Arrays are fussy about type

In [29]:
py_list=[1,1.5,'A']
np_array=np.array(py_list)

In [36]:
print(py_list)

np_array 
# notice below the numbers become str with '' for numpy
# can use astypes to change type 

[1, 1.5, 'A']


array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [37]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [38]:
np_array + 10

array([11, 12, 13, 14, 15])

In [39]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [40]:
py_list_1=[1,2,3,4,5]
py_list_2=[10,20,30,40,50]

np_array_1=np.array(py_list_1)
np_array_2=np.array(py_list_2)

In [41]:
py_list_1 +py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [42]:
np_array_1+np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [43]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [45]:
print(py_list*2)
np_array*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [46]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [47]:
np_array**2

array([ 1,  4,  9, 16, 25])

In [48]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [49]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [51]:
print(py_list==3)
# in python list the question is on the full list if it consists of 3 only
print(np_array==3)
np_array>3
# in numpy array, the elements in the list are checked for the conditions stated

False
[False False  True False False]


array([False, False, False,  True,  True])

In [52]:
py_list>3

TypeError: '>' not supported between instances of 'list' and 'int'

## 2.8 Mathematics

In [53]:
py_list=[1,2,3,4,5]
np_array=np.array(py_list)

In [59]:
print(sum(py_list))
print(max(py_list))
print(min(py_list))
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
np_array.std

15
5
1
15
5
1
3.0


<function ndarray.std>

In [60]:
py_list.sum()

AttributeError: 'list' object has no attribute 'sum'

## Footnotes