<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

- subsetting means to **select**
- indexing refers to selecting _one_ element
- slicing reders to selecting a *range* of elements

In [1]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
py_list=["a1","b2","c3","d4","e5","f6","g7","h8","i9","j10"]
np_array=np.array(py_list) # convert py list to np array

# pick one
# x=py_list # or
x=np_array

In [4]:
x[0]    # first element

np.str_('a1')

In [7]:
x[-1]   # last element

np.str_('j10')

In [8]:
x[1:6]  # index 1 to 5 so it's a [ , ) situation

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [9]:
py_list[1:6:2]  #index 1 to 5 in steps of 2

['b2', 'd4', 'f6']

In [10]:
py_list[:5]    # index 0 to 5

['a1', 'b2', 'c3', 'd4', 'e5']

In [11]:
py_list[::-1]   # reverses the list

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [14]:
np_array=np.array([1,2,3,4,5,6,7,8,9,10])
mask=np_array >3
mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [18]:
np_array[mask]  #only the elements that fulfil mask are shown

array([ 4,  5,  6,  7,  8,  9, 10])

In [19]:
np_array[np_array>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [21]:
np_array[~(np_array>3)]

array([1, 2, 3])

In [20]:
np_array[(np_array>3)&(np_array<8)]     # "&" means "AND"

array([4, 5, 6, 7])

In [22]:
np_array[(np_array<3)|(np_array>8)]

array([ 1,  2,  9, 10])

In [10]:
mask.sum()      #counts number of trues

np.int64(3)

In [9]:
np_array//2 #Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [11]:
np_array%2  #Remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [12]:
np_array[~mask]

array([ 1,  2,  4,  5,  7,  8, 10])

In [14]:
np.logical_and(np_array>3,np_array<3)

array([False, False, False, False, False, False, False, False, False,
       False])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [24]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d=np.array(py_list_2d)

In [25]:
print(py_list_2d[3])
np_array_2d[3]

[4, 'D']


array(['4', 'D'], dtype='<U21')

In [17]:
py_list_2d[3:][0]

[4, 'D']

In [26]:
print(py_list_2d[3][0])
np_array_2d[3,0]

4


np.str_('4')

In [27]:
np_array_2d[3,0]    # Only for Numpy

np.str_('4')

In [28]:
print(py_list_2d[:3])
np_array_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]


array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [30]:
print(py_list_2d[:3][0])
np_array_2d[:3,0]

[1, 'A']


array(['1', '2', '3'], dtype='<U21')

In [19]:
np_array_2d[3:,1]   # Only for Numpy

array(['D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

In [31]:
print(py_list_2d[3:6][0])
print(np_array_2d[3:6,0])
np_array_2d[:,0]

[4, 'D']
['4' '5' '6']


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

## 1.4 Growing lists

In [32]:
x=[1,2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [33]:
x=[1]
x=x+[2]
x=x+[3]
x=x+[4]
x

[1, 2, 3, 4]

In [34]:
x=[1]
x+=[2]
x+=[3]
x+=[4]
x

[1, 2, 3, 4]

In [36]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x
# faster by 1.5 times than first 2

[1, 2, 3, 4]

In [39]:
x=[1,2,3]
x+=[4,5,6]
print(x)
x=[1,2,3]
x.extend([4,5,6])
print(x)
x=[1,2,3]
x.append([4,5,6])
print(x) # append still groups the list of [4,5,6] as a subset

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, [4, 5, 6]]


In [20]:
x=[1,2]+[3]
print(x)
x= x + [2]
print(x)
x= x + [3]
print(x)
x= x + [4]
print(x)
x

[1, 2, 3]
[1, 2, 3, 2]
[1, 2, 3, 2, 3]
[1, 2, 3, 2, 3, 4]


[1, 2, 3, 2, 3, 4]

# Some loose ends

## 1.5 Tuples

In [40]:
a=(1,2,3)   #define tupule

In [45]:
print(a[0]) # data accessible

1


In [46]:
a[0]=-1     # data not changeable

TypeError: 'tuple' object does not support item assignment

In [44]:
a[0]+=[10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

## 1.6 Be VERY careful when copying

In [48]:
x=[1,2,3]
y=x         # wrong 
z=x         # way

In [49]:
x=[1,2,3]
y=x.copy    # correct
z=x.copy    # way

## Footnotes